;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	mwim-beginning
	mwim-end
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	end-of-buffer
	helm-M-x
	ns-copy-including-secondary
	))
